export const REAL_MARKET_GOLDENS = {
  'btcusdt-5m-trend': [
    {
      cursor: 9,
      comparable: {
        ready: true,
        legacyReady: true,
        engineReady: true,
        structureReady: true,
        actionableStructureReady: true,
        boundedRangeReady: false,
        locationContextUsable: false,
        readinessReasons: {
          engine: [],
          structure: [],
          actionable: [],
          range: ['MISSING_RANGE_BOUNDARY'],
          location: ['MISSING_RANGE_BOUNDARY'],
        },
        notReadyReason: null,
        structureAvailability: { level: 'WATCHABLE', limitingFactor: 'ZONE_QUALITY' },
        supportZones: [],
        resistanceZones: [
          {
            id: 'BTCUSDT-5m-R-001',
            role: 'RESISTANCE',
            originalRole: 'RESISTANCE',
            lifecycle: 'FRESH',
            tier: 'WATCHABLE',
            quality: 'LOW',
            low: 61716.74,
            high: 61749,
            mid: 61732.87,
            score: 3,
            originIndex: 5,
            confirmedIndex: 7,
            availableFromIndex: 8,
            touchCount: 0,
            cleanTouchSessions: 0,
            noisyTouchSessions: 0,
            passThroughCount: 0,
            breakCount: 0,
            noisyCrossCount: 0,
            lastRespectedIndex: null,
            brokenAt: null,
            flippedAt: null,
            invalidatedAt: null,
          },
        ],
        transitionZones: [],
        s1: null,
        s2: null,
        r1: {
          id: 'BTCUSDT-5m-R-001',
          role: 'RESISTANCE',
          originalRole: 'RESISTANCE',
          lifecycle: 'FRESH',
          tier: 'WATCHABLE',
          quality: 'LOW',
          low: 61716.74,
          high: 61749,
          mid: 61732.87,
          score: 3,
          originIndex: 5,
          confirmedIndex: 7,
          availableFromIndex: 8,
          touchCount: 0,
          cleanTouchSessions: 0,
          noisyTouchSessions: 0,
          passThroughCount: 0,
          breakCount: 0,
          noisyCrossCount: 0,
          lastRespectedIndex: null,
          brokenAt: null,
          flippedAt: null,
          invalidatedAt: null,
        },
        r2: null,
        warnings: [
          'MISSING_INSTRUMENT_METADATA',
          'NO_VALID_SUPPORT',
          'USING_LOW_QUALITY_RESISTANCE_FALLBACK',
        ],
      },
    },
    {
      cursor: 11,
      comparable: {
        ready: true,
        legacyReady: true,
        engineReady: true,
        structureReady: true,
        actionableStructureReady: true,
        boundedRangeReady: false,
        locationContextUsable: false,
        readinessReasons: {
          engine: [],
          structure: [],
          actionable: [],
          range: ['MISSING_RANGE_BOUNDARY'],
          location: ['MISSING_RANGE_BOUNDARY'],
        },
        notReadyReason: null,
        structureAvailability: { level: 'WATCHABLE', limitingFactor: 'ZONE_QUALITY' },
        supportZones: [],
        resistanceZones: [
          {
            id: 'BTCUSDT-5m-R-001',
            role: 'RESISTANCE',
            originalRole: 'RESISTANCE',
            lifecycle: 'FRESH',
            tier: 'WATCHABLE',
            quality: 'LOW',
            low: 61716.74,
            high: 61749,
            mid: 61732.87,
            score: 3,
            originIndex: 5,
            confirmedIndex: 7,
            availableFromIndex: 8,
            touchCount: 0,
            cleanTouchSessions: 0,
            noisyTouchSessions: 0,
            passThroughCount: 0,
            breakCount: 0,
            noisyCrossCount: 0,
            lastRespectedIndex: null,
            brokenAt: null,
            flippedAt: null,
            invalidatedAt: null,
          },
        ],
        transitionZones: [],
        s1: null,
        s2: null,
        r1: {
          id: 'BTCUSDT-5m-R-001',
          role: 'RESISTANCE',
          originalRole: 'RESISTANCE',
          lifecycle: 'FRESH',
          tier: 'WATCHABLE',
          quality: 'LOW',
          low: 61716.74,
          high: 61749,
          mid: 61732.87,
          score: 3,
          originIndex: 5,
          confirmedIndex: 7,
          availableFromIndex: 8,
          touchCount: 0,
          cleanTouchSessions: 0,
          noisyTouchSessions: 0,
          passThroughCount: 0,
          breakCount: 0,
          noisyCrossCount: 0,
          lastRespectedIndex: null,
          brokenAt: null,
          flippedAt: null,
          invalidatedAt: null,
        },
        r2: null,
        warnings: [
          'MISSING_INSTRUMENT_METADATA',
          'NO_VALID_SUPPORT',
          'USING_LOW_QUALITY_RESISTANCE_FALLBACK',
        ],
      },
    },
  ],
  'ethusdt-15m-medium-vol': [
    {
      cursor: 9,
      comparable: {
        ready: false,
        legacyReady: false,
        engineReady: true,
        structureReady: false,
        actionableStructureReady: false,
        boundedRangeReady: false,
        locationContextUsable: false,
        readinessReasons: {
          engine: [],
          structure: ['NO_PUBLIC_ACTIVE_ZONES'],
          actionable: ['NO_PUBLIC_ACTIVE_ZONES'],
          range: ['NO_PUBLIC_ACTIVE_ZONES'],
          location: ['NO_PUBLIC_ACTIVE_ZONES'],
        },
        notReadyReason: 'NO_PUBLIC_ACTIVE_ZONES',
        structureAvailability: { level: 'NONE', limitingFactor: 'NO_ZONES' },
        supportZones: [],
        resistanceZones: [],
        transitionZones: [],
        s1: null,
        s2: null,
        r1: null,
        r2: null,
        warnings: ['MISSING_INSTRUMENT_METADATA', 'NO_VALID_STRUCTURE'],
      },
    },
    {
      cursor: 11,
      comparable: {
        ready: true,
        legacyReady: true,
        engineReady: true,
        structureReady: true,
        actionableStructureReady: true,
        boundedRangeReady: false,
        locationContextUsable: false,
        readinessReasons: {
          engine: [],
          structure: [],
          actionable: [],
          range: ['MISSING_RANGE_BOUNDARY'],
          location: ['MISSING_RANGE_BOUNDARY'],
        },
        notReadyReason: null,
        structureAvailability: { level: 'WATCHABLE', limitingFactor: 'ZONE_QUALITY' },
        supportZones: [],
        resistanceZones: [
          {
            id: 'ETHUSDT-15m-R-001',
            role: 'RESISTANCE',
            originalRole: 'RESISTANCE',
            lifecycle: 'FRESH',
            tier: 'WATCHABLE',
            quality: 'LOW',
            low: 3384.91,
            high: 3388.82,
            mid: 3386.865,
            score: 3,
            originIndex: 7,
            confirmedIndex: 9,
            availableFromIndex: 10,
            touchCount: 0,
            cleanTouchSessions: 0,
            noisyTouchSessions: 0,
            passThroughCount: 0,
            breakCount: 0,
            noisyCrossCount: 0,
            lastRespectedIndex: null,
            brokenAt: null,
            flippedAt: null,
            invalidatedAt: null,
          },
        ],
        transitionZones: [],
        s1: null,
        s2: null,
        r1: {
          id: 'ETHUSDT-15m-R-001',
          role: 'RESISTANCE',
          originalRole: 'RESISTANCE',
          lifecycle: 'FRESH',
          tier: 'WATCHABLE',
          quality: 'LOW',
          low: 3384.91,
          high: 3388.82,
          mid: 3386.865,
          score: 3,
          originIndex: 7,
          confirmedIndex: 9,
          availableFromIndex: 10,
          touchCount: 0,
          cleanTouchSessions: 0,
          noisyTouchSessions: 0,
          passThroughCount: 0,
          breakCount: 0,
          noisyCrossCount: 0,
          lastRespectedIndex: null,
          brokenAt: null,
          flippedAt: null,
          invalidatedAt: null,
        },
        r2: null,
        warnings: [
          'MISSING_INSTRUMENT_METADATA',
          'NO_VALID_SUPPORT',
          'USING_LOW_QUALITY_RESISTANCE_FALLBACK',
        ],
      },
    },
  ],
  'solusdt-5m-high-vol': [
    {
      cursor: 9,
      comparable: {
        ready: false,
        legacyReady: false,
        engineReady: true,
        structureReady: false,
        actionableStructureReady: false,
        boundedRangeReady: false,
        locationContextUsable: false,
        readinessReasons: {
          engine: [],
          structure: ['NO_PUBLIC_ACTIVE_ZONES'],
          actionable: ['NO_PUBLIC_ACTIVE_ZONES'],
          range: ['NO_PUBLIC_ACTIVE_ZONES'],
          location: ['NO_PUBLIC_ACTIVE_ZONES'],
        },
        notReadyReason: 'NO_PUBLIC_ACTIVE_ZONES',
        structureAvailability: { level: 'NONE', limitingFactor: 'NO_ZONES' },
        supportZones: [],
        resistanceZones: [],
        transitionZones: [],
        s1: null,
        s2: null,
        r1: null,
        r2: null,
        warnings: ['MISSING_INSTRUMENT_METADATA', 'NO_VALID_STRUCTURE'],
      },
    },
    {
      cursor: 11,
      comparable: {
        ready: false,
        legacyReady: false,
        engineReady: true,
        structureReady: true,
        actionableStructureReady: false,
        boundedRangeReady: false,
        locationContextUsable: false,
        readinessReasons: {
          engine: [],
          structure: [],
          actionable: ['NO_PUBLIC_ACTIVE_ZONES'],
          range: ['MISSING_RANGE_BOUNDARY'],
          location: ['MISSING_RANGE_BOUNDARY'],
        },
        notReadyReason: 'NO_PUBLIC_ACTIVE_ZONES',
        structureAvailability: { level: 'CONTEXT_ONLY', limitingFactor: 'ZONE_QUALITY' },
        supportZones: [],
        resistanceZones: [],
        transitionZones: [
          {
            id: 'SOLUSDT-5m-R-001',
            role: 'RESISTANCE',
            originalRole: 'RESISTANCE',
            lifecycle: 'BROKEN',
            tier: 'CONTEXT',
            quality: 'LOW',
            low: 129.09,
            high: 129.71,
            mid: 129.4,
            score: 0,
            originIndex: 7,
            confirmedIndex: 9,
            availableFromIndex: 10,
            touchCount: 1,
            cleanTouchSessions: 0,
            noisyTouchSessions: 0,
            passThroughCount: 1,
            breakCount: 1,
            noisyCrossCount: 0,
            lastRespectedIndex: null,
            brokenAt: '2024-03-01T00:50:00.000Z',
            flippedAt: null,
            invalidatedAt: null,
          },
        ],
        s1: null,
        s2: null,
        r1: null,
        r2: null,
        warnings: [
          'MISSING_INSTRUMENT_METADATA',
          'NO_VALID_RESISTANCE',
          'NO_VALID_STRUCTURE',
          'NO_VALID_SUPPORT',
        ],
      },
    },
  ],
  'sushiusdt-15m-choppy': [
    {
      cursor: 9,
      comparable: {
        ready: true,
        legacyReady: true,
        engineReady: true,
        structureReady: true,
        actionableStructureReady: true,
        boundedRangeReady: false,
        locationContextUsable: false,
        readinessReasons: {
          engine: [],
          structure: [],
          actionable: [],
          range: ['MISSING_RANGE_BOUNDARY'],
          location: ['MISSING_RANGE_BOUNDARY'],
        },
        notReadyReason: null,
        structureAvailability: { level: 'WATCHABLE', limitingFactor: 'ZONE_QUALITY' },
        supportZones: [],
        resistanceZones: [
          {
            id: 'SUSHIUSDT-15m-R-002',
            role: 'RESISTANCE',
            originalRole: 'RESISTANCE',
            lifecycle: 'FRESH',
            tier: 'WATCHABLE',
            quality: 'LOW',
            low: 1.55,
            high: 1.553,
            mid: 1.5515,
            score: 3,
            originIndex: 5,
            confirmedIndex: 7,
            availableFromIndex: 8,
            touchCount: 0,
            cleanTouchSessions: 0,
            noisyTouchSessions: 0,
            passThroughCount: 0,
            breakCount: 0,
            noisyCrossCount: 0,
            lastRespectedIndex: null,
            brokenAt: null,
            flippedAt: null,
            invalidatedAt: null,
          },
        ],
        transitionZones: [],
        s1: null,
        s2: null,
        r1: {
          id: 'SUSHIUSDT-15m-R-002',
          role: 'RESISTANCE',
          originalRole: 'RESISTANCE',
          lifecycle: 'FRESH',
          tier: 'WATCHABLE',
          quality: 'LOW',
          low: 1.55,
          high: 1.553,
          mid: 1.5515,
          score: 3,
          originIndex: 5,
          confirmedIndex: 7,
          availableFromIndex: 8,
          touchCount: 0,
          cleanTouchSessions: 0,
          noisyTouchSessions: 0,
          passThroughCount: 0,
          breakCount: 0,
          noisyCrossCount: 0,
          lastRespectedIndex: null,
          brokenAt: null,
          flippedAt: null,
          invalidatedAt: null,
        },
        r2: null,
        warnings: [
          'MISSING_INSTRUMENT_METADATA',
          'NO_CLEAN_TRADE_LOCATION',
          'NO_VALID_SUPPORT',
          'PRICE_INSIDE_CONTEXT_ZONE',
          'USING_LOW_QUALITY_RESISTANCE_FALLBACK',
        ],
      },
    },
    {
      cursor: 11,
      comparable: {
        ready: true,
        legacyReady: true,
        engineReady: true,
        structureReady: true,
        actionableStructureReady: true,
        boundedRangeReady: false,
        locationContextUsable: false,
        readinessReasons: {
          engine: [],
          structure: [],
          actionable: [],
          range: ['MISSING_RANGE_BOUNDARY'],
          location: ['MISSING_RANGE_BOUNDARY'],
        },
        notReadyReason: null,
        structureAvailability: { level: 'WATCHABLE', limitingFactor: 'ZONE_QUALITY' },
        supportZones: [],
        resistanceZones: [
          {
            id: 'SUSHIUSDT-15m-R-002',
            role: 'RESISTANCE',
            originalRole: 'RESISTANCE',
            lifecycle: 'FRESH',
            tier: 'WATCHABLE',
            quality: 'LOW',
            low: 1.55,
            high: 1.553,
            mid: 1.5515,
            score: 3,
            originIndex: 5,
            confirmedIndex: 7,
            availableFromIndex: 8,
            touchCount: 0,
            cleanTouchSessions: 0,
            noisyTouchSessions: 0,
            passThroughCount: 0,
            breakCount: 0,
            noisyCrossCount: 0,
            lastRespectedIndex: null,
            brokenAt: null,
            flippedAt: null,
            invalidatedAt: null,
          },
        ],
        transitionZones: [
          {
            id: 'SUSHIUSDT-15m-S-001',
            role: 'SUPPORT',
            originalRole: 'SUPPORT',
            lifecycle: 'BROKEN',
            tier: 'CONTEXT',
            quality: 'LOW',
            low: 1.524,
            high: 1.532,
            mid: 1.528,
            score: 0,
            originIndex: 3,
            confirmedIndex: 5,
            availableFromIndex: 6,
            touchCount: 2,
            cleanTouchSessions: 1,
            noisyTouchSessions: 1,
            passThroughCount: 0,
            breakCount: 1,
            noisyCrossCount: 2,
            lastRespectedIndex: 6,
            brokenAt: '2024-03-01T02:30:00.000Z',
            flippedAt: null,
            invalidatedAt: null,
          },
        ],
        s1: null,
        s2: null,
        r1: {
          id: 'SUSHIUSDT-15m-R-002',
          role: 'RESISTANCE',
          originalRole: 'RESISTANCE',
          lifecycle: 'FRESH',
          tier: 'WATCHABLE',
          quality: 'LOW',
          low: 1.55,
          high: 1.553,
          mid: 1.5515,
          score: 3,
          originIndex: 5,
          confirmedIndex: 7,
          availableFromIndex: 8,
          touchCount: 0,
          cleanTouchSessions: 0,
          noisyTouchSessions: 0,
          passThroughCount: 0,
          breakCount: 0,
          noisyCrossCount: 0,
          lastRespectedIndex: null,
          brokenAt: null,
          flippedAt: null,
          invalidatedAt: null,
        },
        r2: null,
        warnings: [
          'MISSING_INSTRUMENT_METADATA',
          'NO_VALID_SUPPORT',
          'USING_LOW_QUALITY_RESISTANCE_FALLBACK',
        ],
      },
    },
  ],
} as const;
